services:
  wavelog-main:
    build: .
    container_name: wavelog-main
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - wavelog-db
    env_file:
      - docker.app.env
      - docker.db.env
    environment: 
      CI_ENV: docker
    volumes:
      - ./storage/config:/var/www/html/application/config/docker
      - ./storage/uploads:/var/www/html/uploads
      - ./storage/userdata:/var/www/html/userdata
    ports:
      - 8086:80
  
  wavelog-db:
    restart: unless-stopped
    image: mariadb:11.3
    networks:
      - internal_network
    env_file: docker.db.env
    volumes:
      - ./.mariadb:/var/lib/mysql

networks:
  default:
  internal_network:
    internal: true
