services:
  app:
    build: .
    command: /start-app.sh
    restart: unless-stopped
    networks:
      - default
      - internal_network
    depends_on:
      - mariadb
    env_file:
      - docker.app.env
      - docker.db.env
    volumes:
      - ./storage/logs:/var/www/html/application/logs
      - ./storage/backup:/var/www/html/backup
      - ./storage/updates:/var/www/html/updates
      - ./storage/uploads:/var/www/html/uploads

  web:
    build: .
    command: /start-web.sh
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - app
    env_file:
      - docker.app.env
    volumes:
      - ./storage/logs:/var/www/html/application/logs
      - ./storage/backup:/var/www/html/backup
      - ./storage/updates:/var/www/html/updates
      - ./storage/uploads:/var/www/html/uploads
    ports:
      - 8082:80

  
  cron:
    build: .
    command: /start-cron.sh
    restart: unless-stopped
    networks:
      - default
      - internal_network

  mariadb:
    restart: unless-stopped
    image: mariadb:10.10
    networks:
      - internal_network
    env_file: docker.db.env
    volumes:
      - ./.mariadb:/var/lib/mysql

networks:
  default:
  internal_network:
    internal: true
